title: Termina
author: Termina developers
feedback_url: https://install.appcenter.ms/users/marquiskurt-outlook.com/apps/termina-macos/distribution_groups/public%20beta%20testing
disqus: termina-game
enable_beta: true

enable_ios_beta: false
enable_macos_beta: true

plugins:
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME